### PR TITLE
did you know that codeflask is terrible

### PR DESCRIPTION
**Pull request by anna-is-cute**
highlight callbacks and no prism

### CODE REVIEW

**Comment by lol768** [comment]
rood

**Comment by lol768** [comment]
you fucker you didn't build it

**Comment by lol768** [comment]
damn you

**Comment by anna-is-cute** [comment]
tbh I don't know how

**Comment by lol768** [comment]
https://github.com/lol768/CodeFlask/commit/8efe436948354a035f99341230c6dfa7b71ab99f

**Pull request merged**
